# Generated by Django 5.2.1 on 2025-06-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineHabilete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeHabilete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Habilete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('criteres_reussite', models.TextField(blank=True, max_length=500, null=True)),
                ('mise_en_place', models.TextField(blank=True, max_length=500, null=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habiletes', to='hab.domainehabilete')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habiletes', to='hab.sport')),
            ],
            options={
                'verbose_name': 'Habileté',
                'verbose_name_plural': 'Habiletés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SystemeNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systemes_notation', to='hab.sport')),
            ],
            options={
                'verbose_name': 'Système de notation',
                'verbose_name_plural': 'Systèmes de notation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='NiveauSportif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
                ('habiletes', models.ManyToManyField(related_name='niveaux_sportifs', to='hab.habilete')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux_sportifs', to='hab.systemenotation')),
            ],
            options={
                'verbose_name_plural': 'Niveaux sportifs',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='domainehabilete',
            name='type_habilite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domaines_habiletes', to='hab.typehabilete'),
        ),
        migrations.CreateModel(
            name='HabiletePersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_habilete', models.CharField(choices=[('A', 'Acquis'), ('E', 'En cours'), ('N', 'Non acquis'), ('I', 'Inconnu')], default='I', max_length=1)),
                ('habilete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habiletes_personne', to='hab.habilete')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habiletes_personne', to='adh.personne')),
            ],
            options={
                'verbose_name': 'Habileté de personne',
                'verbose_name_plural': 'Habiletés des personnes',
                'ordering': ['personne', 'habilete', 'acquisition_habilete'],
                'constraints': [models.UniqueConstraint(fields=('personne', 'habilete'), name='habilete_personne')],
            },
        ),
        migrations.AddConstraint(
            model_name='habilete',
            constraint=models.UniqueConstraint(fields=('nom', 'sport'), name='habilete_de_sport'),
        ),
        migrations.AddConstraint(
            model_name='systemenotation',
            constraint=models.UniqueConstraint(fields=('nom', 'sport'), name='notation_de_sport'),
        ),
        migrations.AddConstraint(
            model_name='niveausportif',
            constraint=models.UniqueConstraint(fields=('nom', 'systeme'), name='niveau_dans_systeme'),
        ),
    ]
