# Generated by Django 5.2.1 on 2025-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typehabilete',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
