# Generated by Django 5.2.1 on 2025-06-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainehabilete',
            options={'ordering': ['nom'], 'verbose_name': "Domaine d'habileté", 'verbose_name_plural': "Domaines d'habiletés"},
        ),
        migrations.AlterModelOptions(
            name='typehabilete',
            options={'ordering': ['nom'], 'verbose_name': "Type d'habileté", 'verbose_name_plural': "Types d'habiletés"},
        ),
    ]
