# Generated by Django 5.2.1 on 2025-07-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab', '0002_typehabilete_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainehabilete',
            old_name='type_habilite',
            new_name='type_habilete',
        ),
    ]
