# Generated by Django 5.2.1 on 2025-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab', '0004_systemenotation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemenotation',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
