# Generated by Django 5.2.1 on 2025-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('type_adhesion', models.CharField(choices=[('F', 'Famille'), ('I', 'Individuelle')], default='F', max_length=1)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150, unique=True)),
                ('bosses', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_naissance', models.CharField(max_length=150, verbose_name='Nom de naissance')),
                ('nom_usage', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom d'usage")),
                ('prenoms_naissance', models.CharField(max_length=250, verbose_name='Prénoms de naissance')),
                ('prenoms_usage', models.CharField(blank=True, max_length=250, null=True, verbose_name="Prénoms d'usage")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('tgram', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('discord', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
    ]
