# Generated by Django 5.2.1 on 2025-05-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startyear', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adh.saison')),
            ],
        ),
    ]
