# Generated by Django 5.2.1 on 2025-05-26 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('fn', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='description',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='saison',
            name='startyear',
        ),
        migrations.AddField(
            model_name='activite',
            name='ski_licence_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saison',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saison',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_age__gte', models.F('min_age'))), name='check_age')],
            },
        ),
        migrations.CreateModel(
            name='PriceForAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tranche_age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adh.agerange')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pass_allowed', models.BooleanField(default=False)),
                ('ouverte', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adh.activite')),
                ('prereqs', models.ManyToManyField(to='adh.prerequ')),
                ('price_ranges', models.ManyToManyField(through='adh.PriceForAge', to='adh.agerange')),
            ],
        ),
        migrations.AddField(
            model_name='priceforage',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adh.variante'),
        ),
        migrations.AddConstraint(
            model_name='priceforage',
            constraint=models.CheckConstraint(condition=models.Q(('max_price__gte', models.F('min_price'))), name='check_price'),
        ),
    ]
