# Generated by Django 5.2.1 on 2025-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adh', '0001_initial'),
        ('hab', '0001_initial'),
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='federations',
            field=models.ManyToManyField(to='lic.federation'),
        ),
        migrations.AddField(
            model_name='personne',
            name='familles',
            field=models.ManyToManyField(to='adh.famille'),
        ),
        migrations.AddField(
            model_name='personne',
            name='habiletes',
            field=models.ManyToManyField(through='hab.HabiletePersonne', to='hab.habilete'),
        ),
        migrations.AddConstraint(
            model_name='personne',
            constraint=models.UniqueConstraint(fields=('nom_naissance', 'prenoms_naissance', 'date_naissance'), name='etat_civil_unique'),
        ),
    ]
