# Generated by Django 5.2.1 on 2025-07-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adh', '0001_initial'),
        ('glo', '0001_initial'),
        ('hab', '0001_initial'),
        ('pan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glo.club'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pan.paiement'),
        ),
        migrations.AddField(
            model_name='personne',
            name='familles',
            field=models.ManyToManyField(to='adh.famille'),
        ),
        migrations.AddField(
            model_name='personne',
            name='habiletes',
            field=models.ManyToManyField(through='hab.HabiletePersonne', to='hab.habilete'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adh.personne'),
        ),
        migrations.AddField(
            model_name='typemembre',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glo.club'),
        ),
        migrations.AddConstraint(
            model_name='personne',
            constraint=models.UniqueConstraint(fields=('nom_naissance', 'prenoms_naissance', 'date_naissance'), name='etat_civil_unique'),
        ),
        migrations.AddConstraint(
            model_name='typemembre',
            constraint=models.UniqueConstraint(fields=('club', 'nom'), name='unique_typemembre_club'),
        ),
    ]
