# Generated by Django 5.2.1 on 2025-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0002_prerequ_rename_description_activite_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saison',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('activite', 'description'), name='unique_activite'),
        ),
    ]
