# Generated by Django 5.2.1 on 2025-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0003_alter_saison_label_variante_unique_activite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variante',
            name='unique_activite',
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.UniqueConstraint(fields=('saison', 'nom'), name='unique_activite_by_season'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('activite', 'description'), name='unique_variante'),
        ),
    ]
