# Generated by Django 5.2.1 on 2025-05-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0004_remove_variante_unique_activite_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activite',
            name='unique_activite_by_season',
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.UniqueConstraint(fields=('saison', 'nom'), name='unique_activite'),
        ),
    ]
