# Generated by Django 5.2.1 on 2025-05-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0005_remove_activite_unique_activite_by_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
