# Generated by Django 5.2.1 on 2025-05-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0006_alter_variante_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saison',
            new_name='Periode',
        ),
    ]
