# Generated by Django 5.2.1 on 2025-05-27 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def load_saisons(apps, schema_editor):
    Saison = apps.get_model("adh", "Saison")
    saison_2024 = Saison(start_year=2024)
    saison_2024.save()
    saison_2025 = Saison(start_year=2025)
    saison_2025.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0007_rename_saison_periode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2025)])),
            ],
        ),
        migrations.RunPython(load_saisons),
        migrations.RemoveConstraint(
            model_name='activite',
            name='unique_activite',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='saison',
            new_name='periode',
        ),
        migrations.AlterField(
            model_name='periode',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.UniqueConstraint(fields=('periode', 'nom'), name='unique_activite'),
        ),
        migrations.AddField(
            model_name='periode',
            name='saison',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='adh.saison'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('saison', 'label'), name='periode_de_saison'),
        ),
    ]
