# Generated by Django 5.2.1 on 2025-05-27 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0008_saison_remove_activite_unique_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='membership_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='priceforage',
            name='max_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='priceforage',
            name='min_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='priceforage',
            constraint=models.CheckConstraint(condition=models.Q(('max_birth__gte', models.F('min_birth'))), name='check_birth'),
        ),
    ]
