# Generated by Django 5.2.1 on 2025-05-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0009_activite_membership_required_priceforage_max_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='price_ranges',
        ),
    ]
