# Generated by Django 5.2.1 on 2025-05-27 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0010_remove_variante_price_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceforage',
            name='max_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='priceforage',
            name='min_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
