# Generated by Django 5.2.1 on 2025-05-27 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0011_alter_priceforage_max_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceforage',
            name='max_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='priceforage',
            name='min_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
