# Generated by Django 5.2.1 on 2025-05-27 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0012_alter_priceforage_max_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceforage',
            name='tranche_age',
        ),
        migrations.RemoveConstraint(
            model_name='priceforage',
            name='check_price',
        ),
        migrations.RemoveConstraint(
            model_name='priceforage',
            name='check_birth',
        ),
        migrations.AlterField(
            model_name='priceforage',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='priceforage',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='priceforage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_price__isnull', True), ('min_price__isnull', True), ('max_price__gte', models.F('min_price')), _connector='OR')), name='check_price'),
        ),
        migrations.AddConstraint(
            model_name='priceforage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_birth__isnull', True), ('min_birth__isnull', True), ('max_birth__gte', models.F('min_birth')), _connector='OR')), name='check_birth'),
        ),
        migrations.DeleteModel(
            name='AgeRange',
        ),
    ]
