# Generated by Django 5.2.1 on 2025-05-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0013_remove_priceforage_tranche_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceForAge',
            new_name='PriceByAge',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='prereqs',
        ),
        migrations.DeleteModel(
            name='Prerequ',
        ),
    ]
