# Generated by Django 5.2.1 on 2025-05-28 22:21

from django.db import migrations, models
from ..models import Periode
from django.template.defaultfilters import slugify

def set_periodes_slugs(apps, schema_editor):
    ps  = Periode.objects.all()
    for p in ps:
        p.slug=slugify(p.label)
        p.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0014_rename_priceforage_pricebyage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saison',
            options={'ordering': ['start_year']},
        ),
        migrations.AddField(
            model_name='periode',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(set_periodes_slugs),
    ]
