# Generated by Django 5.2.1 on 2025-05-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0015_alter_saison_options_periode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='slug',
            field=models.SlugField(default=models.F('label')),
        ),
    ]
