# Generated by Django 5.2.1 on 2025-05-28 23:02

from django.db import migrations, models
from ..models import Activite
from django.template.defaultfilters import slugify

def set_activites_slugs(apps, schema_editor):
    ps  = Activite.objects.all()
    for p in ps:
        p.slug=slugify(p.nom)
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0016_alter_periode_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(set_activites_slugs),
    ]
