# Generated by Django 5.2.1 on 2025-05-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adh', '0017_activite_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='slug',
            field=models.SlugField(default=models.F('nom')),
        ),
    ]
