# Generated by Django 5.2.1 on 2025-07-05 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('alias', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('type_adhesion', models.CharField(choices=[('F', 'Famille'), ('I', 'Individuelle')], default='F', max_length=1)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('start_year', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2024)])),
            ],
            options={
                'ordering': ['start_year'],
            },
        ),
    ]
