# Generated by Django 5.2.1 on 2025-06-30 06:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2024)])),
            ],
            options={
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('visible', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glo.saison')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'constraints': [models.UniqueConstraint(fields=('saison', 'label'), name='periode_de_saison')],
            },
        ),
    ]
