# Generated by Django 5.2.1 on 2025-06-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periode',
        ),
    ]
