# Generated by Django 5.2.1 on 2025-07-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glo', '0001_initial'),
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='federations',
            field=models.ManyToManyField(to='lic.federation'),
        ),
    ]
