# Generated by Django 5.2.1 on 2025-07-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='nom',
            new_name='description',
        ),
    ]
