# Generated by Django 5.2.1 on 2025-07-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glo', '0003_rename_nom_club_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['nom']},
        ),
        migrations.RenameField(
            model_name='club',
            old_name='alias',
            new_name='nom',
        ),
    ]
