# Generated by Django 5.2.1 on 2025-06-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adh', '0001_initial'),
        ('glo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Fédération',
                'verbose_name_plural': 'Fédérations',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='NiveauAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': "Niveau d'assurance",
                'verbose_name_plural': "Niveaux d'assurance",
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='IdentiteFederale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licence', models.CharField(max_length=20)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identites_federales', to='lic.federation')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='adh.personne')),
            ],
            options={
                'verbose_name_plural': 'Identités fédérales',
            },
        ),
        migrations.CreateModel(
            name='LicenceSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validateur', models.CharField(max_length=150)),
                ('date_validation', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences_saisons', to='adh.club')),
                ('identite_federale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences_saisons', to='lic.identitefederale')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences_saisons', to='glo.saison')),
                ('niveau_assurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences_saisons', to='lic.niveauassurance')),
            ],
            options={
                'verbose_name_plural': 'Licences saison',
            },
        ),
        migrations.CreateModel(
            name='TypeLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_licences', to='lic.federation')),
            ],
            options={
                'verbose_name': 'Type de licence',
                'verbose_name_plural': 'Types de licence',
                'ordering': ['alias'],
            },
        ),
        migrations.AddField(
            model_name='niveauassurance',
            name='type_licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux_assurances', to='lic.typelicence'),
        ),
        migrations.AddConstraint(
            model_name='identitefederale',
            constraint=models.UniqueConstraint(fields=('personne', 'federation'), name='idf_personne_fede_unique'),
        ),
        migrations.AddConstraint(
            model_name='identitefederale',
            constraint=models.UniqueConstraint(fields=('numero_licence', 'federation'), name='idf_numlic_fede_unique'),
        ),
        migrations.AddConstraint(
            model_name='licencesaison',
            constraint=models.UniqueConstraint(fields=('identite_federale', 'saison'), name='idf_saison_unique'),
        ),
        migrations.AddConstraint(
            model_name='niveauassurance',
            constraint=models.UniqueConstraint(fields=('alias', 'type_licence'), name='niveau_assurance_uc'),
        ),
    ]
