# Generated by Django 5.2.1 on 2025-07-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='federation',
            old_name='nom',
            new_name='description',
        ),
    ]
