# Generated by Django 5.2.1 on 2025-07-05 15:59

from django.db import migrations, models
from django.template.defaultfilters import slugify


def set_slugs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Federation = apps.get_model("lic", "Federation")
    for f in Federation.objects.all():
        f.slug = slugify(f.nom)
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0002_rename_nom_federation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federation',
            options={'ordering': ['nom'], 'verbose_name': 'Fédération', 'verbose_name_plural': 'Fédérations'},
        ),
        migrations.RenameField(
            model_name='federation',
            old_name='alias',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='typelicence',
            old_name='nom',
            new_name='description',
        ),
        migrations.AddField(
            model_name='federation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(set_slugs),
    ]


