# Generated by Django 5.2.1 on 2025-07-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0003_alter_federation_options_rename_alias_federation_nom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typelicence',
            options={'ordering': ['nom'], 'verbose_name': 'Type de licence', 'verbose_name_plural': 'Types de licence'},
        ),
        migrations.RenameField(
            model_name='typelicence',
            old_name='alias',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='typelicence',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='federation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
