# Generated by Django 5.2.1 on 2025-07-05 16:09

from django.db import migrations, models
from django.template.defaultfilters import slugify

def set_slugs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TypeLicence = apps.get_model("lic", "TypeLicence")
    for f in TypeLicence.objects.all():
        f.slug = slugify(f.nom)
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0004_alter_typelicence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typelicence',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        
        migrations.RunPython(set_slugs),
    ]
