# Generated by Django 5.2.1 on 2025-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0005_typelicence_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typelicence',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
