# Generated by Django 5.2.1 on 2025-07-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0006_federation_url_alter_typelicence_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveauassurance',
            old_name='nom',
            new_name='description',
        ),
        migrations.AddField(
            model_name='niveauassurance',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
