# Generated by Django 5.2.1 on 2025-07-05 16:17

from django.db import migrations, models
from django.template.defaultfilters import slugify

def set_slugs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    mo = apps.get_model("lic", "NiveauAssurance")
    for f in mo.objects.all():
        f.slug = slugify(f.nom)
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0007_rename_nom_niveauassurance_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveauassurance',
            options={'ordering': ['nom'], 'verbose_name': "Niveau d'assurance", 'verbose_name_plural': "Niveaux d'assurance"},
        ),
        migrations.RemoveConstraint(
            model_name='niveauassurance',
            name='niveau_assurance_uc',
        ),
        migrations.RenameField(
            model_name='niveauassurance',
            old_name='alias',
            new_name='nom',
        ),
        migrations.AddConstraint(
            model_name='niveauassurance',
            constraint=models.UniqueConstraint(fields=('nom', 'type_licence'), name='niveau_assurance_uc'),
        ),
        

    ]
