# Generated by Django 5.2.1 on 2025-07-05 16:20

from django.db import migrations, models
from django.template.defaultfilters import slugify

def set_slugs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    mo = apps.get_model("lic", "NiveauAssurance")
    for x in mo.objects.all():
        x.slug = slugify(f"{x.type_licence.slug}-{x.nom}")
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0008_alter_niveauassurance_options_and_more'),
    ]

    operations = [
                migrations.RunPython(set_slugs),
        migrations.AlterField(
            model_name='niveauassurance',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
