# Generated by Django 5.2.1 on 2025-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0009_alter_niveauassurance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveauassurance',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
