# Generated by Django 5.2.1 on 2025-07-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0010_niveauassurance_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identitefederale',
            options={'verbose_name': 'Identité fédérale', 'verbose_name_plural': 'Identités fédérales'},
        ),
    ]
