# Generated by Django 5.2.1 on 2025-06-30 06:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('membership_required', models.BooleanField(default=False)),
                ('slug', models.SlugField(verbose_name='ID Panier')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='PriceByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Né(e) après le ')),
                ('max_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Né(e) avant le ')),
                ('min_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='VarianteActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pass_allowed', models.BooleanField(default=False)),
                ('ouverte', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Variante d'activité",
                'verbose_name_plural': "Variantes d'activités",
            },
        ),
    ]
