# Generated by Django 5.2.1 on 2025-07-05 13:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('membership_required', models.BooleanField(default=False, verbose_name='Adhésion au club organisateur requise ?')),
                ('slug', models.SlugField(unique=True, verbose_name='ID Panier')),
                ('date_debut', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Début de l'activité ")),
                ('date_fin', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Date de fin de l'activité ")),
                ('url_info', models.URLField(blank=True, null=True, verbose_name="Page d'infos")),
                ('multi_date', models.BooleanField(default=False, verbose_name='Multi dates ?')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='Jauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('niveau_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Jauge',
                'verbose_name_plural': 'Jauges',
            },
        ),
        migrations.CreateModel(
            name='PriceByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': "Tarif selon l'âge",
                'verbose_name_plural': 'Tarifs selon les âges',
            },
        ),
        migrations.CreateModel(
            name='VarianteActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description de la variante')),
                ('ouverte', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Début de la variante ')),
                ('date_fin', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de fin de la variante ')),
            ],
            options={
                'verbose_name': "Variante d'activité",
                'verbose_name_plural': "Variantes d'activités",
            },
        ),
    ]
