# Generated by Django 5.2.1 on 2025-07-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('act', '0001_initial'),
        ('glo', '0001_initial'),
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='club_organisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='glo.club'),
        ),
        migrations.AddField(
            model_name='activite',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glo.saison'),
        ),
        migrations.AddField(
            model_name='activite',
            name='type_lic_req',
            field=models.ManyToManyField(related_name='activites', to='lic.typelicence', verbose_name='Licences admises'),
        ),
        migrations.AddField(
            model_name='jauge',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jauges', to='glo.saison'),
        ),
        migrations.AddField(
            model_name='activite',
            name='jauges',
            field=models.ManyToManyField(related_name='activites', to='act.jauge'),
        ),
        migrations.AddField(
            model_name='varianteactivite',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='act.activite'),
        ),
        migrations.AddField(
            model_name='pricebyage',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='act.varianteactivite'),
        ),
        migrations.AddConstraint(
            model_name='jauge',
            constraint=models.UniqueConstraint(fields=('saison', 'nom'), name='unique_jauge'),
        ),
        migrations.AddConstraint(
            model_name='jauge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('niveau_min__isnull', True), ('niveau_max__gte', models.F('niveau_min')), _connector='OR')), name='check_coherence_niveau_jauge'),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.UniqueConstraint(fields=('saison', 'nom'), name='unique_activite'),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_debut__isnull', True), ('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR')), name='check_dates_activites_deb_fin'),
        ),
        migrations.AddConstraint(
            model_name='varianteactivite',
            constraint=models.UniqueConstraint(fields=('activite', 'description'), name='unique_variante'),
        ),
        migrations.AddConstraint(
            model_name='pricebyage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_price__isnull', True), ('min_price__isnull', True), ('max_price__gte', models.F('min_price')), _connector='OR')), name='check_price'),
        ),
        migrations.AddConstraint(
            model_name='pricebyage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_age__isnull', True), ('min_age__isnull', True), ('max_age__gte', models.F('min_age')), _connector='OR')), name='check_age'),
        ),
    ]
