# Generated by Django 5.2.1 on 2025-06-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('act', '0001_initial'),
        ('adh', '0001_initial'),
        ('glo', '0001_initial'),
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='club_organisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='adh.club'),
        ),
        migrations.AddField(
            model_name='activite',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glo.saison'),
        ),
        migrations.AddField(
            model_name='activite',
            name='type_lic_req',
            field=models.ManyToManyField(related_name='activites', to='lic.typelicence'),
        ),
        migrations.AddField(
            model_name='varianteactivite',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='act.activite'),
        ),
        migrations.AddField(
            model_name='pricebyage',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='act.varianteactivite'),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.UniqueConstraint(fields=('periode', 'nom'), name='unique_activite'),
        ),
        migrations.AddConstraint(
            model_name='varianteactivite',
            constraint=models.UniqueConstraint(fields=('activite', 'description'), name='unique_variante'),
        ),
        migrations.AddConstraint(
            model_name='pricebyage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_price__isnull', True), ('min_price__isnull', True), ('max_price__gte', models.F('min_price')), _connector='OR')), name='check_price'),
        ),
        migrations.AddConstraint(
            model_name='pricebyage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_birth__isnull', True), ('min_birth__isnull', True), ('max_birth__gte', models.F('min_birth')), _connector='OR')), name='check_birth'),
        ),
    ]
