# Generated by Django 5.2.1 on 2025-06-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_initial'),
        ('adh', '0002_initial'),
        ('glo', '0002_delete_periode'),
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activite',
            name='unique_activite',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='periode',
        ),
        migrations.AddField(
            model_name='activite',
            name='saison',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='glo.saison'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.UniqueConstraint(fields=('saison', 'nom'), name='unique_activite'),
        ),
    ]
