# Generated by Django 5.2.1 on 2025-07-01 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0003_remove_activite_unique_activite_and_more'),
        ('adh', '0002_initial'),
        ('glo', '0002_delete_periode'),
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date_debut',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Début de l'activité "),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_fin',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Date de fin de l'activité "),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_debut__isnull', True), ('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR')), name='check_dates_activites_deb_fin'),
        ),
    ]
