# Generated by Django 5.2.1 on 2025-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0003_varianteactivite_check_dates_variantes_deb_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteactivite',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début de la variante '),
        ),
        migrations.AlterField(
            model_name='varianteactivite',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de la variante '),
        ),
    ]
