# Generated by Django 5.2.1 on 2025-07-01 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_activite_date_debut_activite_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricebyage',
            name='check_birth',
        ),
        migrations.RemoveField(
            model_name='pricebyage',
            name='max_birth',
        ),
        migrations.RemoveField(
            model_name='pricebyage',
            name='min_birth',
        ),
        migrations.AddField(
            model_name='pricebyage',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pricebyage',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='pricebyage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_age__isnull', True), ('min_age__isnull', True), ('max_age__gte', models.F('min_age')), _connector='OR')), name='check_age'),
        ),
    ]
